GET http://127.0.0.1:8080/api/hello
Accept: application/json

###

GET http://127.0.0.1:8080/api/hello?name=world
Accept: application/json

###

GET http://127.0.0.1:8080/api/hello?name=world
Accept: application/json
Authorization: Basic elephpant I❤️PHP

###

GET http://127.0.0.1:8080/api/item
Accept: application/json
Authorization: Basic elephpant I❤️PHP

# TODO: Script that reads resonse, modifies it, and saves to storage

###

POST http://127.0.0.1:8080/api/item
Accept: application/json
Authorization: Basic elephpant I❤️PHP

# TODO: Send modified data from storage

###
